shared workflows: 'package' instead of 'devel' and 'tarball'
issue https://github.com/externpro/externpro/issues/148

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -87,26 +87,26 @@ jobs:
           path: |
             _bld-${{ env.CMAKE_PRESET }}/CMakeFiles/CMakeConfigureLog.yaml
       -
-        name: Find devel package tarball
-        id: find_tarball
+        name: Find package
+        id: find_package
         if: ${{ inputs.cmake-workflow-preset != 'LinuxReleaseNoInstall' }}
         shell: bash
         run: |
           file=$(pwd)/$(ls _bld-${{ env.CMAKE_PRESET }}/${{ github.event.repository.name }}*-devel.tar.xz)
           if [[ ! -f "$file" ]]; then
-            echo "Tarball not found!" >&2
+            echo "Package not found!" >&2
             exit 1
           fi
           echo "filepath=$file" >> $GITHUB_OUTPUT
           echo "filename=$(basename $file)" >> $GITHUB_OUTPUT
         working-directory: ${{ github.workspace }}
       -
-        name: Upload devel tarball artifact
+        name: Upload package artifact
         if: ${{ inputs.cmake-workflow-preset != 'LinuxReleaseNoInstall' }}
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ steps.find_tarball.outputs.filename }}
-          path: ${{ steps.find_tarball.outputs.filepath }}
+          name: ${{ steps.find_package.outputs.filename }}
+          path: ${{ steps.find_package.outputs.filepath }}
   clean-up:
     needs: [build-docker-image, build]
     if: ${{ needs.build.result == 'success' }}
diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -33,14 +33,14 @@ jobs:
           path: |
             _bld-${{ env.CMAKE_PRESET }}/CMakeFiles/CMakeConfigureLog.yaml
       -
-        name: Find devel package tarball
-        id: find_tarball
+        name: Find package
+        id: find_package
         if: ${{ inputs.cmake-workflow-preset != 'WindowsReleaseNoInstall' }}
         shell: bash
         run: |
           file=$(pwd)/$(ls _bld-${{ env.CMAKE_PRESET }}/${{ github.event.repository.name }}*-devel.tar.xz)
           if [[ ! -f "$file" ]]; then
-            echo "Tarball not found!" >&2
+            echo "Package not found!" >&2
             exit 1
           fi
           echo "filepath=$file" >> $GITHUB_OUTPUT
@@ -52,12 +52,12 @@ jobs:
         if: ${{ inputs.cmake-workflow-preset != 'WindowsReleaseNoInstall' }}
         shell: pwsh
         run: |
-          $windowsPath = '${{ steps.find_tarball.outputs.filepath }}' -replace '^/([a-zA-Z])/', '$1:/' -replace '/', '\'
+          $windowsPath = '${{ steps.find_package.outputs.filepath }}' -replace '^/([a-zA-Z])/', '$1:/' -replace '/', '\'
           echo "windows_path=$windowsPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
       -
-        name: Upload devel tarball artifact
+        name: Upload package artifact
         if: ${{ inputs.cmake-workflow-preset != 'WindowsReleaseNoInstall' }}
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ steps.find_tarball.outputs.filename }}
+          name: ${{ steps.find_package.outputs.filename }}
           path: ${{ steps.convert_path.outputs.windows_path }}
