github/workflows: 'Check for dirty repo' step

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -114,6 +114,15 @@ jobs:
         with:
           name: ${{ steps.find_package.outputs.filename }}
           path: ${{ steps.find_package.outputs.filepath }}
+      -
+        name: Check for dirty repo
+        shell: bash
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Error: Dirty repo detected!"
+            git status
+            exit 1
+          fi
   clean-up:
     needs: [build-docker-image, build]
     if: ${{ needs.build.result == 'success' }}
diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -67,3 +67,12 @@ jobs:
         with:
           name: ${{ steps.find_package.outputs.filename }}
           path: ${{ steps.convert_path.outputs.windows_path }}
+      -
+        name: Check for dirty repo
+        shell: bash
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Error: Dirty repo detected!"
+            git status
+            exit 1
+          fi
